name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
  - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    environment: main_environment
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ WAKATIME_API_KEY }}
          GH_TOKEN: ${{ GH_TOKEN }}
          SHOW_OS: True
          SHOW_UPDATED_DATE: True
